name: Deploy to GitHub Pages

on:
  push:
    branches: [main]  # Se ejecuta al hacer push en "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Descarga tu código
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload files
        uses: actions/upload-pages-artifact@v2
        with:
          path: './'  # Usa la raíz del proyecto
      - name: Deploy
        uses: actions/deploy-pages@v2